library(ape)
library(data.table)
library(magrittr)
library(ggplot2)
library(ggpubr)
library(parallel)
library(ggtree)
source('scripts/nb_outbreak.R')
theme_set(theme_bw(base_size=15))

# Alert probability -------------------------------------------------------

### Let X(i)~Nb(R0,kappa)
R0=3.4
kappa=0.1
v=R0+kappa*R0^2  #=pr/(1-p)^2   #variance
r=(R0^2)/(v^2-R0)               #size

### X(1),...,X(N) will be transmission events
### Let q be the probability of hospitalization
q=0.02

### Let A be the threshold for alerts: doctors
### identify patients after A show up with unusual symptoms
A=5

### What is the probability that any given transmission event
### generates enough patients to trigger alert?

### Let Z~Binom(X,q) be the number of patients generated by xmsn event
### E[Z]=R0*q
### P{Z>A}?

mx=1e4


PZ=data.table('Cluster Size'=rep(1:mx,times=3),'q'=rep(c(0.02,0.05,0.1),each=mx))
PZ$`Alert Probability` <- 1-pbinom(A,size=PZ$`Cluster Size`,prob=PZ$q)  #P{Z>A|X=x}
PZ[,`Medical Detection Probability`:=factor(paste0(q*100,'%'),levels=c('2%','5%','10%'))]
PZ[,`Cluster Probability`:=dnbinom(`Cluster Size`,size = r,mu=R0)]

g_PAlert=ggplot(PZ,aes(`Cluster Size`,`Alert Probability`))+
            geom_line(lwd=2,aes(color=`Medical Detection Probability`))+
            theme(legend.position=c(0.7,0.3))+
            scale_color_manual(values=c('black',rgb(0.48,0.48,0.48),'grey'))+
            scale_x_continuous(limits=c(0,600))+
            ggtitle('Probability of Alert vs. Cluster Size')

### With P{Alert|X}, we can estimate the marginal E[X|Alert==1]
### This is the size of cluster we expect given we were alerted by the cluster
PZ[,weighted.mean(`Cluster Size`,
                  w=`Alert Probability`*`Cluster Probability`),
   by='Medical Detection Probability']   

# #note: R's weighted-mean normalizes weights w to 1
# weighted.mean(1:3,w=c(.1,.4,.5)) = weighted.mean(1:3,w=c(1,4,5))

Exp_cluster_size <- function(q=0.02,A=5,mx=1e4,r.=r,R0.=R0){
  x=1:mx
  ap=1-pbinom(A,x,q)
  cp=dnbinom(x,size=r,mu=R0)
  return(weighted.mean(x,ap*cp))
}


ExpC=expand.grid('q'=seq(.02,1,by=0.1), 'A'=seq(1,50,by=1)) %>% as.data.table
ExpC[,X:=Exp_cluster_size(q,A),by=c('q','A')]
g_Xq= ggplot(ExpC[A %in% c(1,10,50)],aes(q,X))+
          geom_line(aes(lty=factor(A)),lwd=2)+
          scale_x_continuous('Medical Detection Probability')+
          scale_y_continuous('Alerting Cluster Size',trans='log',breaks=c(1,10,100))+
  ggtitle('Cluster size vs Case Detection Probability')+
  theme(legend.position=c(0.77,0.75))

g_XA= ggplot(ExpC[q %in% c(0.02,0.22,0.52)],aes(A,X))+
  geom_line(aes(lty=factor(q)),lwd=2)+
  scale_x_continuous('Alert Threshold')+
  scale_y_continuous('Alerting Cluster Size',trans='log',breaks=c(1,10,100))+
  ggtitle('Cluster Size vs. Alert Threshold')+
  theme(legend.position=c(0.13,0.75))

ggarrange(g_PAlert,ggarrange(g_Xq,g_XA,ncol=2),nrow=2)